version: "3.8"

services:
  api:
    build: ./api
    restart: on-failure
    env_file:
      - .env

  aria2:
    build: ./aria2
    restart: on-failure
    env_file:
      - .env

  postgres:
    image: postgres:15
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
